let strValue1="33"
let strValue2="abc"
let strValue3=""
let strValue4=null
let strValue5=undefined
let numValue1=Number(strValue1)
console.log(typeof numValue1)
console.log(numValue1)
let numValue2=Number(strValue2)
console.log(typeof numValue2)
console.log(numValue2)
let numValue3=Number(strValue3)
console.log(typeof numValue3)
console.log(numValue3)
let numValue4=Number(strValue4)
console.log(typeof numValue4)
console.log(numValue4)
let numValue5=Number(strValue5)
console.log(typeof numValue5)
console.log(numValue5)
let boolValue1=Boolean(strValue1)
console.log(typeof boolValue1)
console.log(boolValue1)
let boolValue2=Boolean(strValue2)
console.log(typeof boolValue2)
console.log(boolValue2)
let boolValue3=Boolean(strValue3)
console.log(typeof boolValue3)
console.log(boolValue3)
let boolValue4=Boolean(strValue4)
console.log(typeof boolValue4)
console.log(boolValue4)
let boolValue5=Boolean(strValue5)
console.log(typeof boolValue5)
console.log(boolValue5)
let numVal=33
let strVal=String(numVal)
console.log(typeof strVal)
console.log(strVal)
let boolVal=0
let strVal2=String(boolVal)
console.log(typeof strVal)
console.log(strVal)